# Generated by Django 6.1.1 on 2026-09-19 04:59

import shop.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shop.upload.UUIDUploadTo('products')),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=shop.upload.UUIDUploadTo('thumbnails')),
        ),
    ]
