# Generated by Django 4.2.7 on 2025-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'is_active'), name='unique_active_cart_per_user'),
        ),
    ]
