# Generated by Django 5.2.2 on 2025-06-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_options_remove_order_costumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری پستی'),
        ),
    ]
