# Generated by Django 5.2.2 on 2025-06-12 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_payment_order_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_pain',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cash', 'پرداخت نقدی'), ('bank_transfer', 'انتقال بانکی'), ('wallet', 'کیف پول')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(max_length=100, verbose_name='شماره پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
